FROM node:16 as build

LABEL version="0.0.1"
LABEL description="React Frontend for the gig crud API"

WORKDIR /app
COPY . ./

COPY ./package.json ./
RUN npm install --only=prod
RUN npm run build


FROM nginx:1.21.6-alpine
COPY --from=build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf 
COPY ./default.conf /etc/nginx/conf.d/default.conf
EXPOSE 4010
CMD ["nginx", "-g", "daemon off;"]