FROM node:14-alpine3.10

LABEL version="0.0.1"
LABEL description="React Frontend for the gig crud API"

WORKDIR /app
COPY ./package.json ./
RUN npm install --only=prod
COPY . ./
RUN npm run build


# FROM nginx:1.16.0-alpine
# COPY /app/build /usr/share/nginx/html
# EXPOSE 4012
# CMD ["nginx", "-g", "daemon off;"]